[[constraint]]
  name = "github.com/hashicorp/terraform"
  version = "0.10.8"

[[constraint]]
  name = "github.com/cattail/databricks-sdk-go"
  revision = "221e2c6f93f84291c67e17c48f48a28ebd97ad89"

[prune]
  go-tests = true
  unused-packages = true
