[[constraint]]
  branch = "master"
  name = "github.com/betabandido/databricks-sdk-go"

[[constraint]]
  name = "github.com/hashicorp/terraform"
  version = "0.11.3"

[prune]
  go-tests = true
  unused-packages = true
